### ISSUE TITLE
Error while launching 

### ISSUE THREAD

**Issue by hessaHamad** [balamuruganky/wit_imu_ros#1]
Dear, 

thank you for providing this driver. 
I have faced an error during launching. I tried to solve it by enabling the ports in my virtual box but i still face the error 
![IMG_7608](https://github.com/balamuruganky/wit_imu_ros/assets/122529202/12ada228-52e5-43a6-a8fb-798713052bd1)

Im using:
Macbook pro (2019) 
Ubuntu 18.04 (through virtual box)
ROS Melodic
Note: I'm connecting the imu to ttl-usb adapter then usb-type c adapter

**Comment by balamuruganky** [comment]
Basic question : Did you add dialout group to root? It sounds me like a permission issue. Please execute "sudo usermod -aG dialout $USER" and try. Thanks.

**Comment by balamuruganky** [comment]
@hessaHamad : Any update, please?

**Comment by hessaHamad** [comment]
Hello, 
Thank you, the port is opened now but im facing another issue 
![image](https://github.com/balamuruganky/wit_imu_ros/assets/122529202/80c0bf3d-3d04-4411-82df-027d5fa41e38)

please help

**Comment by balamuruganky** [comment]
Check the baud rate please. If the baud rate is not as configured in the ROS package, then change it accordingly. Thanks.

**Comment by hessaHamad** [comment]
I checked it, its configured already
If you can give me any details or another solution help me please
