### ISSUE TITLE
Error while getting the data

### ISSUE THREAD

**Issue by hessaHamad** [balamuruganky/wit_imu_ros#2]
Hello,
i have been facing this issue when i try to launch, 
The port is opened but still bo data is showing 

![IMG_7757](https://github.com/balamuruganky/wit_imu_ros/assets/122529202/93cc92eb-d2b6-40b6-b96e-0e74b0461d47)

**Comment by balamuruganky** [comment]
@hessaHamad : Please check the baud rate and change it accordingly in the configurations. Thanks.

**Comment by balamuruganky** [comment]
<WIT_ROS_DRIVER_PATG>/wit901.yaml

serial_baud_rate needs to be changed accordingly.

**Comment by balamuruganky** [comment]
@hessaHamad  : Hope it works.
